### ISSUE TITLE
Invalid address(0) check in `view` function?

### ISSUE THREAD

**Issue by Schwartz10** [wadealexc/fevmate#1]
As far as I can tell, this check is unnecessary - the `balanceOf(address(0))` would just be `0`.  However, not sure if removing this check would be dangerous to a contract that consumes it.

https://github.com/wadealexc/fevmate/blob/main/contracts/token/ERC721/ERC721.sol#L153

**Comment by wadealexc** [comment]
Totally agree with you - I can't stand `view`/`pure` methods that revert unnecessarily. But this check is a part of the ERC721 spec, so it's possible someone, somewhere relies on the behavior.

Both OpenZeppelin and solmate have this check, too.

So, as much as I think it's dumb, I think it needs to stay there.
